SELECT
    LISTING_ID,
    LISTING_NAME,
    ROOM_TYPE,
    CASE WHEN MINIMUM_NIGHTS = 0 THEN 1 ELSE MINIMUM_NIGHTS END AS MINIMUM_NIGHTS,
    HOST_ID,
    CAST(PRICE_STR AS BIGINT) AS PRICE,
    CREATED_AT,
    UPDATED_AT
FROM {{ ref('src_listings') }}